# --- Channel State Database ---
CHANNEL_STATE_DATABASE_ID = "25405f3bbeea8052a963cf49344bff05"

# --- Channel State Database Properties ---
STATE_FOLLOWERS_ID = "Cq%5Dt"
STATE_REACTIONS_ID = "DG%5Bm"
STATE_VIEWS_ID = "dok%5C"
STATE_SHARES_ID = "rCCN"
STATE_DATE_ID = "%5Eq_%5D"
STATE_HANDLE_ID = "title"

# --- Channel Timeseries Database ---
CHANNEL_TIMESERIES_DATABASE_ID = "25405f3bbeea802796bdc9aaca15b443"

# --- Channel Timeseries Database Properties ---
CHANNEL_TIMESERIES_JOINED_ID = "%40fZy"
CHANNEL_TIMESERIES_DATE_ID = "Uuy%60"
CHANNEL_TIMESERIES_MUTE_ID = "bOdb"
CHANNEL_TIMESERIES_LEFT_ID = "hxHR"
CHANNEL_TIMESERIES_TOTAL_FOLLOWERS_ID = "sIG%3F"
CHANNEL_TIMESERIES_HANDLE_ID = "title"

# --- List of Channels ---
CHANNELS_LIST_DATABASE_ID = "25405f3bbeea80bdbaf0fe03ece2aab6"
